services:
  - type: web
    name: realtime-chat-backend
    env: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /admin/login/
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: realtime-chat-backend.onrender.com,.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://realtime-chat-frontend-oodz.onrender.com,https://realtime-chat-backend-oing.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://realtime-chat-frontend-oodz.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: realtime-chat-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

  - type: web
    name: realtime-chat-frontend
    env: static
    rootDir: front
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://realtime-chat-backend-oing.onrender.com/api


databases:
  - name: realtime-chat-db
    plan: free
